"""
Sovereign Trade Ledger — Cryptographically Signed Trade Log
============================================================
Every signal generated by this system is stamped with a unique signal_id
and signed with a local RSA private key. This creates a tamper-evident,
cryptographically verifiable chain of provenance:

    Signal Generated → SIGNED (timestamp + payload + signature)
         ↓
    Alert Sent → signal_id embedded in Telegram message
         ↓
    Trade Placed → order comment = signal_id (TradeLocker)
         ↓
    Trade Closes → outcome stamped back onto the signed record
         ↓
    Any trade WITHOUT a matching signal_id = ROGUE TRADE ⚠️

Key Store: ~/.sovereign_keys/
  - sovereign_private.pem  (never leaves this machine)
  - sovereign_public.pem   (can be shared for verification)

Security Note: The private key is generated locally on first run.
It is NOT committed to git (added to .gitignore automatically).
"""

import os
import json
import uuid
import hashlib
import logging
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ── Key Storage ──────────────────────────────────────────────────────────────
KEY_DIR = Path.home() / ".sovereign_keys"
PRIVATE_KEY_PATH = KEY_DIR / "sovereign_private.pem"
PUBLIC_KEY_PATH  = KEY_DIR / "sovereign_public.pem"

# ── DB Path ───────────────────────────────────────────────────────────────────
# Re-uses the same database path as the rest of the system
from src.core.config import Config
LEDGER_DB_PATH = Config.DB_PATH


def _ensure_keys() -> tuple:
    """
    Generates RSA key pair on first run, or loads existing keys.
    Returns (private_key, public_key) as cryptography objects.
    """
    try:
        from cryptography.hazmat.primitives.asymmetric import rsa, padding
        from cryptography.hazmat.primitives import serialization, hashes
    except ImportError:
        logger.error("[TradeLedger] 'cryptography' package not installed. Run: pip install cryptography")
        raise

    KEY_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)

    if PRIVATE_KEY_PATH.exists():
        # Load existing keys
        with open(PRIVATE_KEY_PATH, "rb") as f:
            private_key = serialization.load_pem_private_key(f.read(), password=None)
        with open(PUBLIC_KEY_PATH, "rb") as f:
            public_key = serialization.load_pem_public_key(f.read())
        logger.debug("[TradeLedger] Keys loaded from ~/.sovereign_keys/")
    else:
        # Generate new 2048-bit RSA key pair
        private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        public_key  = private_key.public_key()

        with open(PRIVATE_KEY_PATH, "wb") as f:
            f.write(private_key.private_bytes(
                serialization.Encoding.PEM,
                serialization.PrivateFormat.PKCS8,
                serialization.NoEncryption()
            ))
        PRIVATE_KEY_PATH.chmod(0o600)  # Owner read-only

        with open(PUBLIC_KEY_PATH, "wb") as f:
            f.write(public_key.public_bytes(
                serialization.Encoding.PEM,
                serialization.PublicFormat.SubjectPublicKeyInfo
            ))

        logger.info(f"[TradeLedger] 🔑 New sovereign key pair generated at {KEY_DIR}")
        logger.info(f"[TradeLedger] Public key fingerprint: {_fingerprint(public_key)}")

    return private_key, public_key


def _fingerprint(public_key) -> str:
    """Returns a short SHA-256 fingerprint of the public key for display."""
    from cryptography.hazmat.primitives import serialization
    der = public_key.public_bytes(
        serialization.Encoding.DER,
        serialization.PublicFormat.SubjectPublicKeyInfo
    )
    h = hashlib.sha256(der).hexdigest()
    return ':'.join(h[i:i+4] for i in range(0, 16, 4))


def _sign_payload(private_key, payload: dict) -> str:
    """
    Signs a JSON-serialized payload with SHA-256 + RSA.
    Returns a hex-encoded signature string.
    """
    from cryptography.hazmat.primitives.asymmetric import padding
    from cryptography.hazmat.primitives import hashes

    canonical = json.dumps(payload, sort_keys=True, default=str).encode('utf-8')
    signature = private_key.sign(canonical, padding.PKCS1v15(), hashes.SHA256())
    return signature.hex()


def _verify_signature(public_key, payload: dict, signature_hex: str) -> bool:
    """Verifies a payload signature. Returns True if valid."""
    from cryptography.hazmat.primitives.asymmetric import padding
    from cryptography.hazmat.primitives import hashes
    from cryptography.exceptions import InvalidSignature

    try:
        canonical  = json.dumps(payload, sort_keys=True, default=str).encode('utf-8')
        signature  = bytes.fromhex(signature_hex)
        public_key.verify(signature, canonical, padding.PKCS1v15(), hashes.SHA256())
        return True
    except InvalidSignature:
        return False
    except Exception as e:
        logger.error(f"[TradeLedger] Verification error: {e}")
        return False


# ── DB Setup ──────────────────────────────────────────────────────────────────

def _init_ledger_table():
    """Creates the signed_ledger table if it doesn't exist."""
    conn = sqlite3.connect(LEDGER_DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS signed_ledger (
            signal_id     TEXT PRIMARY KEY,
            timestamp     TEXT NOT NULL,
            symbol        TEXT NOT NULL,
            direction     TEXT NOT NULL,
            pattern       TEXT,
            ai_score      REAL,
            entry_price   REAL,
            stop_loss     REAL,
            take_profit   REAL,
            payload_hash  TEXT NOT NULL,
            signature     TEXT NOT NULL,
            outcome       TEXT DEFAULT 'PENDING',
            trade_id      TEXT,
            pnl           REAL,
            is_rogue      INTEGER DEFAULT 0,
            volume_spike  REAL DEFAULT 1.0,
            true_smt      TEXT,
            shadow_regime TEXT,
            notes         TEXT
        )
    """)
    # Migrations
    try:
        c.execute("ALTER TABLE signed_ledger ADD COLUMN volume_spike REAL DEFAULT 1.0")
    except sqlite3.OperationalError: pass
    try:
        c.execute("ALTER TABLE signed_ledger ADD COLUMN true_smt TEXT")
    except sqlite3.OperationalError: pass
    try:
        c.execute("ALTER TABLE signed_ledger ADD COLUMN shadow_regime TEXT")
    except sqlite3.OperationalError: pass
    
    conn.commit()
    conn.close()


# ── Public API ───────────────────────────────────────────────────────────────

class TradeLedger:
    """
    Singleton-style ledger for signing and verifying trade signals.

    Usage:
        ledger = TradeLedger()

        # When a signal fires:
        signal_id = ledger.sign_signal(setup, ai_score)

        # When a trade closes:
        ledger.stamp_outcome(signal_id, trade_id, pnl, outcome='WIN')

        # When a trade has no matching signal:
        ledger.flag_rogue(trade_id)

        # Verify any record:
        is_valid = ledger.verify(signal_id)
    """

    def __init__(self):
        self._private_key, self._public_key = _ensure_keys()
        self._fingerprint = _fingerprint(self._public_key)
        _init_ledger_table()
        logger.info(f"[TradeLedger] ✅ Active | Key: {self._fingerprint}")

    def sign_signal(self, setup: dict, ai_score: float) -> str:
        """
        Creates a cryptographically signed record for a new signal.
        Returns the unique signal_id (embed this in your Telegram alert + order comment).
        """
        signal_id = f"SIG-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}-{setup['symbol'].replace('/', '')}-{setup.get('direction', 'X')[:1]}-{uuid.uuid4().hex[:6].upper()}"

        payload = {
            'signal_id':   signal_id,
            'timestamp':   datetime.utcnow().isoformat(),
            'symbol':      setup.get('symbol', ''),
            'direction':   setup.get('direction', setup.get('bias', '')),
            'pattern':     setup.get('pattern', ''),
            'ai_score':    ai_score,
            'entry_price': setup.get('entry', 0.0),
            'stop_loss':   setup.get('stop_loss', 0.0),
            'take_profit': setup.get('target', setup.get('tp1', 0.0)),
            'volume_spike': setup.get('volume_spike', 1.0),
            'true_smt':     setup.get('true_smt'),
            'shadow_regime': setup.get('shadow_regime', 'Unknown')
        }

        payload_hash = hashlib.sha256(
            json.dumps(payload, sort_keys=True, default=str).encode()
        ).hexdigest()

        signature = _sign_payload(self._private_key, payload)

        conn = sqlite3.connect(LEDGER_DB_PATH)
        try:
            conn.execute("""
                INSERT INTO signed_ledger
                (signal_id, timestamp, symbol, direction, pattern, ai_score,
                 entry_price, stop_loss, take_profit, payload_hash, signature,
                 volume_spike, true_smt, shadow_regime)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                signal_id,
                payload['timestamp'],
                payload['symbol'],
                payload['direction'],
                payload['pattern'],
                payload['ai_score'],
                payload['entry_price'],
                payload['stop_loss'],
                payload['take_profit'],
                payload_hash,
                signature,
                payload['volume_spike'],
                payload['true_smt'],
                payload['shadow_regime']
            ))
            conn.commit()
        finally:
            conn.close()

        logger.info(f"[TradeLedger] ✍️  Signed signal: {signal_id} | Score: {ai_score}")
        return signal_id

    def stamp_outcome(self, signal_id: str, trade_id: str, pnl: float, outcome: str = 'UNKNOWN'):
        """
        Links a closed trade back to its originating signal.
        Outcome: 'WIN', 'LOSS', 'BREAKEVEN', 'PARTIAL'
        """
        conn = sqlite3.connect(LEDGER_DB_PATH)
        try:
            conn.execute("""
                UPDATE signed_ledger
                SET outcome = ?, trade_id = ?, pnl = ?
                WHERE signal_id = ?
            """, (outcome.upper(), trade_id, pnl, signal_id))
            conn.commit()
            updated = conn.execute(
                "SELECT changes()"
            ).fetchone()[0]
        finally:
            conn.close()

        if updated:
            logger.info(f"[TradeLedger] 📌 Outcome stamped: {signal_id} → {outcome} | PnL: {pnl:+.2f}")
        else:
            logger.warning(f"[TradeLedger] ⚠️ No signal found for ID: {signal_id}")

    def flag_rogue(self, trade_id: str, notes: str = ""):
        """
        Flags a trade that appeared in TradeLocker with NO matching signal.
        This is the 'rogue trade' detector.
        """
        ts = datetime.utcnow().isoformat()
        rogue_id = f"ROGUE-{trade_id}-{uuid.uuid4().hex[:6]}"

        # Create a ROGUE record with no signature (the absence IS the evidence)
        conn = sqlite3.connect(LEDGER_DB_PATH)
        try:
            conn.execute("""
                INSERT OR IGNORE INTO signed_ledger
                (signal_id, timestamp, symbol, direction, pattern, ai_score,
                 entry_price, stop_loss, take_profit, payload_hash, signature,
                 outcome, trade_id, is_rogue, notes)
                VALUES (?, ?, 'UNKNOWN', 'UNKNOWN', 'ROGUE_TRADE', 0,
                        0, 0, 0, 'NO_SIGNAL', 'NO_SIGNATURE',
                        'ROGUE', ?, 1, ?)
            """, (rogue_id, ts, trade_id, notes))
            conn.commit()
        finally:
            conn.close()

        logger.warning(
            f"[TradeLedger] 🚨 ROGUE TRADE FLAGGED: trade_id={trade_id} | "
            f"Record={rogue_id} | No matching signed signal."
        )
        return rogue_id

    def verify(self, signal_id: str) -> dict:
        """
        Cryptographically verifies a ledger record.
        Returns {'valid': bool, 'signal_id': str, 'details': dict}
        """
        conn = sqlite3.connect(LEDGER_DB_PATH)
        conn.row_factory = sqlite3.Row
        try:
            row = conn.execute(
                "SELECT * FROM signed_ledger WHERE signal_id = ?", (signal_id,)
            ).fetchone()
        finally:
            conn.close()

        if not row:
            return {'valid': False, 'signal_id': signal_id, 'details': 'Not found in ledger.'}

        row = dict(row)

        # Reconstruct the original payload
        payload = {
            'signal_id':   row['signal_id'],
            'timestamp':   row['timestamp'],
            'symbol':      row['symbol'],
            'direction':   row['direction'],
            'pattern':     row['pattern'],
            'ai_score':    row['ai_score'],
            'entry_price': row['entry_price'],
            'stop_loss':   row['stop_loss'],
            'take_profit': row['take_profit'],
            'volume_spike': row.get('volume_spike', 1.0),
            'true_smt':     row.get('true_smt'),
            'shadow_regime': row.get('shadow_regime', 'Unknown')
        }

        # If it was logged as ROGUE, no signature to verify
        if row.get('is_rogue'):
            return {'valid': False, 'signal_id': signal_id, 'is_rogue': True, 'details': row}

        is_valid = _verify_signature(self._public_key, payload, row['signature'])
        return {
            'valid': is_valid,
            'signal_id': signal_id,
            'is_rogue': False,
            'details': row,
            'key_fingerprint': self._fingerprint,
        }

    def get_unmatched_rogue_trades(self) -> list[dict]:
        """
        Returns all trades flagged as rogue (no signed signal match).
        Use this for the daily audit report.
        """
        conn = sqlite3.connect(LEDGER_DB_PATH)
        conn.row_factory = sqlite3.Row
        try:
            rows = conn.execute(
                "SELECT * FROM signed_ledger WHERE is_rogue = 1 ORDER BY timestamp DESC LIMIT 50"
            ).fetchall()
            return [dict(r) for r in rows]
        finally:
            conn.close()

    def get_provenance_report(self, signal_id: str) -> str:
        """
        Returns a human-readable provenance report for a signal.
        Useful for copy-pasting to a prop firm or investor.
        """
        result = self.verify(signal_id)
        if not result['valid']:
            return f"❌ Signal {signal_id} could not be verified.\nDetails: {result.get('details', 'Unknown')}"

        d = result['details']
        report = f"""
╔══════════════════════════════════════════════╗
║       SOVEREIGN SIGNAL PROVENANCE REPORT     ║
╠══════════════════════════════════════════════╣
  Signal ID    : {d['signal_id']}
  Timestamp    : {d['timestamp']} UTC
  Symbol       : {d['symbol']}
  Direction    : {d['direction']}
  Pattern      : {d['pattern']}
  AI Score     : {d['ai_score']}/10
  Entry Price  : {d['entry_price']}
  Stop Loss    : {d['stop_loss']}
  Take Profit  : {d['take_profit']}
╠══════════════════════════════════════════════╣
  Trade ID     : {d.get('trade_id', 'Not yet linked')}
  Outcome      : {d.get('outcome', 'PENDING')}
  PnL          : {f"${d.get('pnl', 0):+.2f}" if d.get('pnl') is not None else 'Pending'}
╠══════════════════════════════════════════════╣
  Signature    : ✅ VALID
  Key Print    : {result['key_fingerprint']}
  Verified At  : {datetime.utcnow().isoformat()} UTC
╚══════════════════════════════════════════════╝
        """.strip()

        return report

    @property
    def public_key_fingerprint(self) -> str:
        return self._fingerprint
